### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO) and LLVM BOLT

### ISSUE THREAD

**Issue by zamazan4ik** [a-croco-stolyarov/thalassa#1]
Hi!

That's just an idea of how to (possibly) improve the performance of Thalassa even further!

Recently I did many Profile-Guided Optimization (PGO) benchmarks on multiple projects - the results are available [here](https://github.com/zamazan4ik/awesome-pgo). Here you can find different applications from different domains that were accelerated with PGO: compilers (like GCC, Clang), databases, and much more. So that's why I think it's worth trying to apply PGO to Thalassa.

I can suggest the following things to do:
* Evaluate PGO's results on Thalassa.
* If PGO helps to achieve better performance - add a note to Thalassa documentation (possibly to the README file) about that. In this case, users and maintainers will be aware of another optimization opportunity for Thalassa for their own workloads.
* Provide PGO integration into the build scripts. It can help users and maintainers easily apply PGO for their own workloads.

After PGO, I can suggest evaluating [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md) as an additional optimization step after PGO.

**Comment by a-croco-stolyarov** [comment]
Real programmers don't need this shit.
